In [23]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [24]:
data=pd.read_csv(r'C:\Users\hamit\Desktop\Project4\Sales Transaction v.4a.csv')

In [25]:
df=pd.DataFrame(data)

In [26]:
df.head(20)

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country
0,581482,12/9/2019,22485,Set Of 2 Wooden Market Crates,21.47,12,17490.0,United Kingdom
1,581475,12/9/2019,22596,Christmas Star Wish List Chalkboard,10.65,36,13069.0,United Kingdom
2,581475,12/9/2019,23235,Storage Tin Vintage Leaf,11.53,12,13069.0,United Kingdom
3,581475,12/9/2019,23272,Tree T-Light Holder Willie Winkie,10.65,12,13069.0,United Kingdom
4,581475,12/9/2019,23239,Set Of 4 Knick Knack Tins Poppies,11.94,6,13069.0,United Kingdom
5,581475,12/9/2019,21705,Bag 500g Swirly Marbles,10.65,24,13069.0,United Kingdom
6,581475,12/9/2019,22118,Joy Wooden Block Letters,11.53,18,13069.0,United Kingdom
7,581475,12/9/2019,22119,Peace Wooden Block Letters,12.25,12,13069.0,United Kingdom
8,581475,12/9/2019,22217,T-Light Holder Hanging Lace,10.65,12,13069.0,United Kingdom
9,581475,12/9/2019,22216,T-Light Holder White Lace,10.55,24,13069.0,United Kingdom
10,581475,12/9/2019,22380,Toy Tidy Spaceboy,11.06,20,13069.0,United Kingdom
11,581475,12/9/2019,22442,Grow Your Own Flowers Set Of 3,12.25,12,13069.0,United Kingdom
12,581475,12/9/2019,22664,Toy Tidy Dolly Girl Design,11.06,20,13069.0,United Kingdom
13,581475,12/9/2019,22721,Set Of 3 Cake Tins Sketchbook,12.25,12,13069.0,United Kingdom
14,581475,12/9/2019,22723,Set Of 6 Herb Tins Sketchbook,11.53,12,13069.0,United Kingdom
15,581475,12/9/2019,22785,Squarecushion Cover Pink Union Jack,11.53,12,13069.0,United Kingdom
16,581475,12/9/2019,22955,36 Foil Star Cake Cases,11.06,24,13069.0,United Kingdom
17,581475,12/9/2019,23141,Triple Wire Hook Pink Heart,11.06,12,13069.0,United Kingdom
18,581475,12/9/2019,22956,36 Foil Heart Cake Cases,11.06,24,13069.0,United Kingdom
19,581475,12/9/2019,22581,Wood Stocking Christmas Scandispot,10.55,48,13069.0,United Kingdom

In [27]:
dateFormat = '%m/%d/%Y'
df['Date'] = pd.to_datetime(df['Date'],format = dateFormat)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 536350 entries, 0 to 536349
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   TransactionNo  536350 non-null  object
 1   Date           536350 non-null  datetime64[ns]
 2   ProductNo      536350 non-null  object
 3   ProductName    536350 non-null  object
 4   Price          536350 non-null  float64
 5   Quantity       536350 non-null  int64
 6   CustomerNo     536295 non-null  float64
 7   Country        536350 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 32.7+ MB

In [28]:
df.isnull().sum()

TransactionNo     0
Date              0
ProductNo         0
ProductName       0
Price             0
Quantity          0
CustomerNo       55
Country           0
dtype: int64

In [7]:
df['Total_price']= df['Quantity']*df['Price']

In [8]:
df

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country,Total_price
0,581482,2019-12-09,22485,Set Of 2 Wooden Market Crates,21.47,12,17490.0,United Kingdom,257.64
1,581475,2019-12-09,22596,Christmas Star Wish List Chalkboard,10.65,36,13069.0,United Kingdom,383.40
2,581475,2019-12-09,23235,Storage Tin Vintage Leaf,11.53,12,13069.0,United Kingdom,138.36
3,581475,2019-12-09,23272,Tree T-Light Holder Willie Winkie,10.65,12,13069.0,United Kingdom,127.80
4,581475,2019-12-09,23239,Set Of 4 Knick Knack Tins Poppies,11.94,6,13069.0,United Kingdom,71.64
...,...,...,...,...,...,...,...,...,...
536345,C536548,2018-12-01,22168,Organiser Wood Antique White,18.96,-2,12472.0,Germany,-37.92
536346,C536548,2018-12-01,21218,Red Spotty Biscuit Tin,14.09,-3,12472.0,Germany,-42.27
536347,C536548,2018-12-01,20957,Porcelain Hanging Bell Small,11.74,-1,12472.0,Germany,-11.74
536348,C536548,2018-12-01,22580,Advent Calendar Gingham Sack,16.35,-4,12472.0,Germany,-65.40
536349,C536548,2018-12-01,22767,Triple Photo Frame Cornice,20.45,-2,12472.0,Germany,-40.90

In [9]:
# split data into effective sales and cancellation

In [10]:
df_positive=df.loc[df['Quantity']>0 ]
df_positive

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country,Total_price
0,581482,2019-12-09,22485,Set Of 2 Wooden Market Crates,21.47,12,17490.0,United Kingdom,257.64
1,581475,2019-12-09,22596,Christmas Star Wish List Chalkboard,10.65,36,13069.0,United Kingdom,383.40
2,581475,2019-12-09,23235,Storage Tin Vintage Leaf,11.53,12,13069.0,United Kingdom,138.36
3,581475,2019-12-09,23272,Tree T-Light Holder Willie Winkie,10.65,12,13069.0,United Kingdom,127.80
4,581475,2019-12-09,23239,Set Of 4 Knick Knack Tins Poppies,11.94,6,13069.0,United Kingdom,71.64
...,...,...,...,...,...,...,...,...,...
536320,536585,2018-12-01,37449,Ceramic Cake Stand + Hanging Cakes,20.45,2,17460.0,United Kingdom,40.90
536321,536590,2018-12-01,22776,Sweetheart 3 Tier Cake Stand,20.45,1,13065.0,United Kingdom,20.45
536322,536590,2018-12-01,22622,Box Of Vintage Alphabet Blocks,20.45,2,13065.0,United Kingdom,40.90
536323,536591,2018-12-01,37449,Ceramic Cake Stand + Hanging Cakes,20.45,1,14606.0,United Kingdom,20.45
536324,536597,2018-12-01,22220,Cake Stand Lovebird 2 Tier White,20.45,1,18011.0,United Kingdom,20.45

In [14]:
sales= df_positive.to_csv(r'C:\Users\hamit\Desktop\Project4\sales_clean.csv')

In [11]:
df_negative=df.loc[df['Quantity']<0 ]
df_negative

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country,Total_price
1616,C581484,2019-12-09,23843,Paper Craft Little Birdie,6.19,-80995,16446.0,United Kingdom,-501359.05
1617,C581490,2019-12-09,22178,Victorian Glass Hanging T-Light,6.19,-12,14397.0,United Kingdom,-74.28
1618,C581490,2019-12-09,23144,Zinc T-Light Holder Stars Small,6.04,-11,14397.0,United Kingdom,-66.44
1619,C581568,2019-12-09,21258,Victorian Sewing Box Large,6.19,-5,15311.0,United Kingdom,-30.95
1620,C581569,2019-12-09,84978,Hanging Heart Jar T-Light Holder,6.19,-1,17315.0,United Kingdom,-6.19
...,...,...,...,...,...,...,...,...,...
536345,C536548,2018-12-01,22168,Organiser Wood Antique White,18.96,-2,12472.0,Germany,-37.92
536346,C536548,2018-12-01,21218,Red Spotty Biscuit Tin,14.09,-3,12472.0,Germany,-42.27
536347,C536548,2018-12-01,20957,Porcelain Hanging Bell Small,11.74,-1,12472.0,Germany,-11.74
536348,C536548,2018-12-01,22580,Advent Calendar Gingham Sack,16.35,-4,12472.0,Germany,-65.40
536349,C536548,2018-12-01,22767,Triple Photo Frame Cornice,20.45,-2,12472.0,Germany,-40.90

In [12]:
df_positive_local=df_positive.loc[df_positive['Country']=='United Kingdom']
df_positive_local

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country,Total_price
0,581482,2019-12-09,22485,Set Of 2 Wooden Market Crates,21.47,12,17490.0,United Kingdom,257.64
1,581475,2019-12-09,22596,Christmas Star Wish List Chalkboard,10.65,36,13069.0,United Kingdom,383.40
2,581475,2019-12-09,23235,Storage Tin Vintage Leaf,11.53,12,13069.0,United Kingdom,138.36
3,581475,2019-12-09,23272,Tree T-Light Holder Willie Winkie,10.65,12,13069.0,United Kingdom,127.80
4,581475,2019-12-09,23239,Set Of 4 Knick Knack Tins Poppies,11.94,6,13069.0,United Kingdom,71.64
...,...,...,...,...,...,...,...,...,...
536320,536585,2018-12-01,37449,Ceramic Cake Stand + Hanging Cakes,20.45,2,17460.0,United Kingdom,40.90
536321,536590,2018-12-01,22776,Sweetheart 3 Tier Cake Stand,20.45,1,13065.0,United Kingdom,20.45
536322,536590,2018-12-01,22622,Box Of Vintage Alphabet Blocks,20.45,2,13065.0,United Kingdom,40.90
536323,536591,2018-12-01,37449,Ceramic Cake Stand + Hanging Cakes,20.45,1,14606.0,United Kingdom,20.45
536324,536597,2018-12-01,22220,Cake Stand Lovebird 2 Tier White,20.45,1,18011.0,United Kingdom,20.45

In [20]:
sales= df_positive_local.to_csv(r'C:\Users\hamit\Desktop\Project4\sales_local_clean.csv', index=False)

In [16]:
df_positive_foreign=df_positive.loc[df_positive['Country']!='United Kingdom']
df_positive_foreign

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country,Total_price
20,581476,2019-12-09,23198,Pantry Magnetic Shopping List,11.53,48,12433.0,Norway,553.44
21,581476,2019-12-09,23197,Sketchbook Magnetic Shopping List,11.74,24,12433.0,Norway,281.76
22,581476,2019-12-09,23184,Bull Dog Bottle Opener,15.32,8,12433.0,Norway,122.56
23,581476,2019-12-09,23168,Classic Cafe Sugar Dispenser,11.53,12,12433.0,Norway,138.36
24,581476,2019-12-09,23167,Small Ceramic Top Storage Jar,10.96,96,12433.0,Norway,1052.16
...,...,...,...,...,...,...,...,...,...
534617,536540,2018-12-01,21889,Wooden Box Of Dominoes,11.53,24,14911.0,EIRE,276.72
534618,536540,2018-12-01,21891,Traditional Wooden Skipping Rope,11.53,12,14911.0,EIRE,138.36
534619,536541,2018-12-01,21915,Red Harmonica In Box,11.53,12,14911.0,EIRE,138.36
536310,536540,2018-12-01,22968,Rose Cottage Keepsake Box,20.45,4,14911.0,EIRE,81.80
536311,536540,2018-12-01,22622,Box Of Vintage Alphabet Blocks,20.45,6,14911.0,EIRE,122.70